---

- name: Mantle
  become: yes
  hosts: 127.0.0.1
  vars:
    nvm_version: 0.34.0
    node_version: 11.14.0
    nvm_path: "{{ ansible_env.HOME }}/.nvm"
    node_path: "{{ nvm_path }}/versions/v{{ node_version }}/bin/node"
  tasks:
  - name: print out the hostname of target
    command: hostname
  - name: update the apt package index 
    apt: update_cache=yes
  - name: upgrade system packages
    apt: upgrade=yes
  - name: Check for NVM
    stat:
      path: "{{ nvm_path }}"
    register: nvm_details
  - name: Check NVM Version
    shell: . {{ nvm_path }}/nvm.sh && nvm --version | grep {{nvm_version}}
    ignore_errors: True
    register: nvm_version_correct
    when: nvm_details.stat.exists == True
  - name: Trigger NVM Update
    file: path={{ nvm_path }} state=absent
    when: nvm_version_correct is failed
  - name: Install Current NVM Version
    shell: >
      curl -o- https://raw.githubusercontent.com/creationix/nvm/v{{ nvm_version }}/install.sh | bash
    args:
      creates: "{{ ansible_env.HOME }}/.nvm"
  - name: Install correct Node Version
    shell: . {{ nvm_path }}/nvm.sh && nvm install {{node_version}}
    args:
      creates: "{{ node_path }}"
  - name: Make correct Node alias
    shell: . {{ nvm_path }}/nvm.sh && nvm alias default node

