---

- name: Mantle
  hosts: 127.0.0.1
  become: yes
  become_user: mantle
  user: 
  vars:
    nvm_version: 0.34.0
    node_version: 11.14.0
    nvm_dir: "{{ ansible_env.HOME }}/.nvm"
    nvm_path: "{{ nvm_dir }}/nvm.sh"
    node_dir: "{{ nvm_dir }}/versions/v{{ node_version }}"
    node_path: "{{ node_dir }}/bin/node"
    pm2_path: "{{ node_dir }}/bin/pm2"
  tasks:
  - name: apt-get update/upgrade
    become: yes
    become_user: root
    apt: 
      upgrade: yes
      update_cache: yes
  - name: Check for NVM
    stat:
      path: "{{ nvm_path }}"
    register: nvm_details
  - name: Check NVM Version
    shell: . {{ nvm_path }} && nvm --version | grep {{nvm_version}}
    ignore_errors: True
    register: nvm_version_correct
    when: nvm_details.stat.exists == True
  - name: Trigger NVM Update
    file: path={{ nvm_path }} state=absent
    when: nvm_version_correct is failed
  - name: Ensure ~/.nvm exists
    file: path={{ nvm_dir }} state=directory
  - name: Install Current NVM Version
    shell: >
      curl -o- https://raw.githubusercontent.com/creationix/nvm/v{{ nvm_version }}/install.sh | bash
  - name: Install correct Node Version
    become_user: root
    shell: . {{ nvm_path }} && nvm install {{node_version}}
    args:
      creates: "{{ node_path }}"
      executable: /bin/bash
  - name: Make correct Node alias
    shell: . {{ nvm_path }} && nvm alias default node
    args:
      executable: /bin/bash

