---

- name: Mantle
  become: yes
  hosts: 127.0.0.1
  vars:
    nvm_version: 0.33.0
    nvm_path: "{{ ansible_env.HOME }}/.nvm"
  tasks:
  - name: print out the hostname of target
    command: hostname
  - name: update the apt package index 
    apt: update_cache=yes
  - name: upgrade system packages
    apt: upgrade=yes
  - name: Check for NVM
    stat:
      path: "{{ nvm_path }}"
    register: nvm_details
  - name: Check NVM Version
    shell: . {{ ansible_env.HOME }}/.bashrc && nvm --version
    register: nvm_current_version
    when: nvm_details.stat.exists == True
  - name: Trigger NVM Update
    file: path={{ nvm_path }} state=absent
    when: nvm_current_version.stdout != nvm_version
  - name: Ensure NVM Installed
    shell: >
      curl -o- https://raw.githubusercontent.com/creationix/nvm/v{{ nvm_version }}/install.sh | bash
    args:
      creates: "{{ ansible_env.HOME }}/.nvm"
      
