---

- name: Mantle
  hosts: 127.0.0.1
  become: yes
  become_user: mantle
  user: 
  vars:
    nvm_version: 0.34.0
    node_version: 11.14.0
    pm2_version: 3.5.0
    nvm_dir: "{{ ansible_env.HOME }}/.nvm"
    nvm_path: "{{ nvm_dir }}/nvm.sh"
    node_dir: "{{ nvm_dir }}/versions/node/v{{ node_version }}"
    node_modules : "{{ node_dir }}/lib/node_modules"
    node_path: "{{ node_dir }}/bin/node"
    npm_path: "{{ node_dir }}/bin/npm"
    pm2_path: "{{ node_dir }}/bin/pm2"
  tasks:
  - name: APT is up to date
    become: yes
    become_user: root
    apt: 
      upgrade: yes
      update_cache: yes
  - name: NVM is present
    stat:
      path: "{{ nvm_path }}"
    register: nvm_details
  - name: Check NVM Version
    shell: . {{ nvm_path }} && nvm --version | grep {{nvm_version}}
    ignore_errors: True
    register: nvm_version_correct
    when: nvm_details.stat.exists == True
  - name: NVM is correct Version
    file: path={{ nvm_path }} state=absent
    when: nvm_version_correct is failed
  - name: Ensure ~/.nvm exists
    file: path={{ nvm_dir }} state=directory
  - name: Install Current NVM Version
    shell: >
      curl -o- https://raw.githubusercontent.com/creationix/nvm/v{{ nvm_version }}/install.sh | bash
    args:
      creates: "{{ nvm_path }}"
      executable: /bin/bash
  - name: Node Version is Installed
    shell: . ~/.bashrc && nvm install {{node_version}}
    args:
      creates: "{{ node_path }}"
      executable: /bin/bash
  - name: Node Alias is correct
    shell: . {{ nvm_path }} && nvm alias default node
    args:
      executable: /bin/bash
  - name: PM2 is installed
    yarn: 
      name: pm2
      global: yes
      production: yes
      version: "{{ pm2_version }}"
      executable: "{{ npm_path }}"
  - name: PiHole configuration file is Present
    copy:
      src: ./files/etc.pihole.setupVars.conf
      dest: /etc/pihole/setupVars.conf
      force: yes

